version: '3.7'

services:
  nats:
    image: nats:latest
    #command: "-c /etc/nats/nats.conf --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    ports:
    - "4222:4222"
    - "8222:8222"
    - "6222:6222"

  nats2:
    image: nats:latest
    ports:
    - "4223:4222"
    - "8223:8222"
    - "6223:6222"