version: '3.5'
services:
  nats1:
    container_name: nats1
    image: nats
    ports:
      - "8222:8222"
    command: "-http_port 8222 --server_name NATS --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:6222 -c /etc/server.conf"
    volumes:
      - ./server.conf:/etc/server.conf
      - ./auth.conf:/etc/auth.conf
      #- ./accounts.conf:/etc/accounts.conf
    networks: ["nats"]

  nats2:
    container_name: nats2
    image: nats
    command: "--server_name N2 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -c /etc/server.conf"
    volumes:
      - ./server.conf:/etc/server.conf
      - ./auth.conf:/etc/auth.conf
      #- ./accounts.conf:/etc/accounts.conf
    networks: ["nats"]
    depends_on: ["nats1"]

  nats3:
    container_name: nats3
    image: nats
    command: "--server_name N3 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -c /etc/server.conf"
    volumes:
      - ./server.conf:/etc/server.conf
      - ./auth.conf:/etc/auth.conf
      #- ./accounts.conf:/etc/accounts.conf
    networks: ["nats"]
    depends_on: ["nats1"]

networks:
  nats:
    name: nats
