version: '3.5'
services:
  nats:
    container_name: nats
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--server_name NATS --cluster_name JSC --cluster nats://0.0.0.0:6222 --http_port 8222 -p 4222 -c /etc/server.conf"
    volumes:
      - ./server.conf:/etc/server.conf
      #- ./auth.conf:/etc/auth.conf
      - ./accounts.conf:/etc/accounts.conf
    networks: ["nats"]

  nats2:
    container_name: nats2
    image: nats
    ports:
      - "4223:4222"
    command: "--server_name N2 --cluster_name NATS  --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -p 4222 -c /etc/server.conf"
    volumes:
      - ./server.conf:/etc/server.conf
      #- ./auth.conf:/etc/auth.conf
      - ./accounts.conf:/etc/accounts.conf --> js --js --sd /data
    networks: ["nats"]
    depends_on: ["nats"]

  nats3:
    container_name: nats3
    image: nats
    ports:
      - "4224:4222"
    command: "--server_name N3 --cluster_name NATS  --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -p 4222 -c /etc/server.conf"
    volumes:
      - ./server.conf:/etc/server.conf
      #- ./auth.conf:/etc/auth.conf
      - ./accounts.conf:/etc/accounts.conf
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats
